core/src/com/agateau/pixelwheels/GameWorld.java
=> Set possibility to roll any specific bonus always greater than zero

core/src/com/agateau/pixelwheels/racer/PlayerPilot.java
=> Activating a bonus requires a button press instead of holding the button

android/assets/po/fr.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/src/gplay/com/agateau/pixelwheels/android/StoreConfigurator.java, core/src/com/agateau/pixelwheels/Constants.java, core/src/com/agateau/pixelwheels/screens/ConfigScreen.java
Rework the way support info is stored to make its texts follow translation changes.
=> Fix translation of support info

android/assets/po/bn.po, android/assets/po/es.po, android/assets/po/fr.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/assets/po/zh_CN.po, android/assets/screens/credits.gdxui, android/assets/ui/languages.xml, core/src/com/agateau/translations/PoParser.java
Integrate Chinese translation from #143. Thanks @OliverLew!
=> Integrate Chinese translation

android/assets/po/bn.po, android/assets/po/es.po, android/assets/po/fr.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/assets/po/zh_CN.po, android/assets/screens/credits.gdxui
The last PR of Chinese translation was set to auto merge (I understand you want to test the font first), so I didn't get the chance to keep it up-to-date. Also, I fixed the missing colon after "Chinese". I changed my name displayed in the app to "Lu Xu", which is the same as the one I put in copyright information in the .po file. The current username is not formal.
=> update zh_CN translation, and minor fixes.

android/assets/ui/languages.xml
=> Translate Bengali language string

android/assets/po/pl.po, core-tests/src/com/agateau/translations/PoParserTests.java, core/src/com/agateau/translations/PoParser.java
=> Fix plural formula for Polish translation

Makefile
Should be YearMonthDay, not YearDayMonth. Stupid me.
=> Fix date format

core/src/com/agateau/pixelwheels/gameinput/GamepadInputHandler.java, core/src/com/agateau/pixelwheels/gameinput/InputMapperInputHandler.java, core/src/com/agateau/pixelwheels/gameinput/KeyboardInputHandler.java, core/src/com/agateau/pixelwheels/screens/KeyboardConfigScreen.java
This can happen if one of the other player input handler is not a KeyboardInputHandler.
While I was at it, refactor input handlers a bit.
Fixes #178
=> Fix crash in keyboard config

android/src/main/com/agateau/pixelwheels/android/AndroidLauncher.java
=> Fix Android 11 statusbar not disappearing when switching between apps

android/assets/vehicles/rocket.xml, docs/vehicles.md
This PR makes sure the Rocket car cannot get stuck on thin walls.
Fixes #174.
=> Fix stuck rocket

android/assets/po/bn.po, android/assets/po/es.po, android/assets/po/fr.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/zh_CN.po, android/assets/screens/credits.gdxui, android/assets/ui/languages.xml, core/src/com/agateau/translations/PoParser.java
Adds new Russian translation. Closes #190
=> New Russian translation

.changes/unreleased/Developers-20220307-082248.yaml, build.gradle, core/src/com/agateau/libgdx/AgcTmxMapLoader.java, core/src/com/agateau/pixelwheels/map/LapPositionTableIO.java, core/src/com/agateau/pixelwheels/map/Track.java, core/src/com/agateau/pixelwheels/map/WaypointStore.java, tools/README.md, tools/src/com/agateau/pixelwheels/tools/LapPositionTableGenerator.java, tools/src/com/agateau/pixelwheels/tools/trackeditor/EditorAction.java, tools/src/com/agateau/pixelwheels/tools/trackeditor/README.md, tools/src/com/agateau/pixelwheels/tools/trackeditor/TrackEditor.java, tools/src/com/agateau/pixelwheels/tools/trackeditor/TrackEditorScreen.java, tools/src/com/agateau/pixelwheels/tools/trackeditor/TrackIO.java, tools/trackeditor
This PR adds a track "editor". For now it can only edit sections, but being dedicated to it makes it faster at doing so than Tiled.
=> Add track "editor"

.changes/unreleased/Fixed-20220310-171802.yaml, core-tests/build.gradle, core-tests/src/com/agateau/pixelwheels/TranslationTest.java, core-tests/src/com/agateau/utils/TestGdxFiles.java, core/src/com/agateau/translations/PoParser.java
Plural formula was wrong once again. To ensure this can't happen anymore,
I added both formulas and a unit-test to check all .po files are loadable.
=> Fix polish translation not being loaded

tools/src/com/agateau/pixelwheels/tools/trackeditor/README.md, tools/src/com/agateau/pixelwheels/tools/trackeditor/TrackEditorScreen.java
- trackeditor: use tab/shift+tab to change current section
- trackeditor: add a way to delete sections
=> Track Editor improvements

.changes/unreleased/Fixed-20220309-193911.yaml, .changes/unreleased/Fixed-20220309-194558.yaml, core/src/com/agateau/pixelwheels/Constants.java, core/src/com/agateau/pixelwheels/bonus/Mine.java, core/src/com/agateau/pixelwheels/racer/VehicleRenderer.java, core/src/com/agateau/pixelwheels/racer/Wheel.java
- Mines no longer look like they are floating when dropped in water
- Do not draw skidmarks on top of water
=> Water improvements

android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/assets/po/zh_CN.po, android/assets/screens/credits.gdxui, android/assets/ui/languages.xml
<s>**DO NOT MERGE!**
There are some minor glitches and I've not tested all in-game screens yet.
I'm just opening the PR as draft now to avoid double work by multiple users.
I'll test and finish this PR in the next few days…</s>
=> German translation (de_DE)

android/assets/po/messages.pot, tools/po-update
- Avoid empty `msgid ""` lines in messages.pot.
- Remove the POT-Creation-Date entry: it is just useless diff noise. Git holds the same information.
=> Improve message.pot formatting

android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/pl.po, android/assets/po/zh_CN.po
Multiple formatting improvements and other improvements (REALLY big PR to follow the #233, see commit extended description for more info)
=> Multiple translations improvements

.changes/unreleased/Fixed-20220608-222351.yaml, core/src/com/agateau/pixelwheels/Languages.java, core/src/com/agateau/utils/PlatformUtils.java
- Fix opening logs on Windows
- Fix crash when a translation is not available
Fixes #225
=> Fix "open log folder" button on Windows

android/assets/po/de.po
Just a quick shot as draft. I'll update the missing vehicles in the next few days…
=> Update German translation (v0.23.0)

android/assets/po/de.po
Reference: https://github.com/agateau/pixelwheels/pull/238#issuecomment-1173125861
=> Fix German translation

.changes/unreleased/Added-20220721-184638.yaml, android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/sv.po, android/assets/po/zh_CN.po, android/assets/screens/credits.gdxui, android/assets/ui/languages.xml
Opening this PR on behalf of Sanchez, who sent me their Swedish translation!
=> Add Swedish translation

android/assets/po/es.po
=> Fix Spanish translation

core/src/com/agateau/pixelwheels/racer/AIPilot.java
- Modernize AIPilot
- AIPilot: Fix wrong target when checking for mines on the left side
=> aipilot fixes

android/assets/screens/debug.gdxui, core/src/com/agateau/pixelwheels/PwGame.java, core/src/com/agateau/pixelwheels/debug/Debug.java, core/src/com/agateau/pixelwheels/gamesetup/QuickRaceMaestro.java, core/src/com/agateau/pixelwheels/screens/DebugScreen.java
- DebugScreen: Clean ups
- debug: Add debug option to refresh assets on restart
=> refresh on restart

.changes/unreleased/Changed-20220923-143413.yaml, android/assets/po/messages.pot, tools/po-update
- Add changelog entry
- po-update: remove indent options, it causes too many conflicts
=> translation fixes

.github/workflows/main.yml, ci/check-changelog
=> Add changelog CI check

.changes/unreleased/Added-20220930-232645.yaml, core-tests/src/com/agateau/utils/DesktopDirsTests.java, core/src/com/agateau/pixelwheels/Constants.java, core/src/com/agateau/pixelwheels/GameConfig.java, core/src/com/agateau/utils/DesktopDirs.java, core/src/com/agateau/utils/FileUtils.java, desktop/src/com/agateau/pixelwheels/desktop/DesktopLauncher.java
Migrate config file from .config/agateau.com/pixelwheels.conf to
$XDG_CONFIG_HOME/pixelwheels/pixelwheels.conf.
=> Add support for XDG Base Directory environment variables

core/src/com/agateau/pixelwheels/racer/Vehicle.java
- Make sure vehicles can't get stuck by turbo cells
- Fix issues found by Android Studio
=> avoid turbo repeat

android/assets/po/de.po
(Updated translation not tested yet but it doesn't matter for only 4 changed strings.)
_PS: Nice new track! I like it_ 😃
=> Update German PO file

android/assets/po/ru.po
=> Translate missing strings

android/assets/po/hu.po
As mentioned in https://github.com/agateau/pixelwheels/pull/309
=> Wrap button text for Hungarian language

.changes/unreleased/Fixed-20230109-080309.yaml, core/src/com/agateau/pixelwheels/racescreen/GameWorldImpl.java, core/src/com/agateau/pixelwheels/racescreen/RaceScreen.java
- Fix stuttering
- Fix PerformanceCounters spamming logs
=> fix stuttering

.changes/unreleased/Fixed-20230113-085946.yaml, core/src/com/agateau/pixelwheels/racescreen/GameWorldImpl.java
- cleanup: remove dead code
- Fix incorrect player rank on 2nd or 3rd race of championship
=> fix wrong rank on 2nd race

android/assets/ui/languages.xml
See https://github.com/agateau/pixelwheels/pull/303#issuecomment-1366056509
=> Fix Esperanto font

.changes/unreleased/Added-20230215-090241.yaml, android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/eo.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/hu.po, android/assets/po/it_IT.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/sv.po, android/assets/po/tr.po, android/assets/po/zh_CN.po, android/assets/screens/credits.gdxui, android/assets/ui/languages.xml
Add Italian translation by @chipechop, see #325.
=> Add an Italian translation

.changes/unreleased/Fixed-20230217-082645.yaml, core/src/com/agateau/pixelwheels/screens/KeyboardConfigScreen.java
=> Fix crash when editing configuration keys

.changes/unreleased/Added-20230509-084407.yaml, android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/eo.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/hu.po, android/assets/po/it_IT.po, android/assets/po/messages.pot, android/assets/po/nl.po, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/sv.po, android/assets/po/tr.po, android/assets/po/zh_CN.po, android/assets/screens/credits.gdxui, android/assets/ui/languages.xml
=> Added Dutch translation

.changes/unreleased/Fixed-20230522-183938.yaml, android/assets/maps/flood.tmx, core/src/com/agateau/pixelwheels/map/PolylineMapObjectWalker.java
- PolyLineMapObjectWalker: support rotated objects
- Flood: plug hole in tire barrier
=> fix hole in flood

.changes/unreleased/Fixed-20230529-191931.yaml, core/src/com/agateau/pixelwheels/PwGame.java
=> Reload reward rules translations when language changes

android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/eo.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/hu.po, android/assets/po/it_IT.po, android/assets/po/messages.pot, android/assets/po/nl.po, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/sv.po, android/assets/po/tr.po, android/assets/po/zh_CN.po, android/assets/screens/credits.gdxui
@lukmarcus Thanks for all the bugs! :wink:
=> Add Marek to the "Special Thanks" section

.changes/unreleased/Fixed-20230616-184222.yaml, android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/eo.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/hu.po, android/assets/po/it_IT.po, android/assets/po/messages.pot, android/assets/po/nl.po, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/sv.po, android/assets/po/tr.po, android/assets/po/zh_CN.po, core/src/com/agateau/pixelwheels/racescreen/RaceScreen.java, core/src/com/agateau/pixelwheels/screens/ConfigScreen.java, core/src/com/agateau/pixelwheels/screens/MainMenuScreen.java, core/src/com/agateau/ui/menu/ButtonMenuItem.java, core/src/com/agateau/ui/menu/Menu.java
- fix: do not allow focusing a disabled button menu item
- Fix language change not working while racing by disabling it
=> no lang change while playing

core/src/com/agateau/pixelwheels/screens/DebugScreen.java
=> Document how to use the free camera

.changes/unreleased/Changed-20230730-122119.yaml, android/AndroidManifest.xml, android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/eo.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/hu.po, android/assets/po/it_IT.po, android/assets/po/messages.pot, android/assets/po/nl.po, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/sv.po, android/assets/po/tr.po, android/assets/po/zh_CN.po, android/assets/screens/notenoughgamepads.gdxui
=> Improve android keyboard support

android/assets/po/nl.po
=> Updated Dutch translation

android/assets/po/tr.po
Sorry for opening another pr, i wish i tested it before.
=> Fix translations after testing

android/src/main/com/agateau/pixelwheels/android/AndroidLogExporter.java, core-tests/src/com/agateau/pixelwheels/LogExporterUtilsTest.java, core/src/com/agateau/pixelwheels/LogExporterUtils.java, core/src/com/agateau/pixelwheels/screens/ConfigScreen.java
- Log preferences before exporting logs
- AndroidLogExporter: fix odd warnings in logcat
=> improve log report

.changes/unreleased/Fixed-20230915-075956.yaml, android/assets/screens/finishedoverlay.gdxui, core/src/com/agateau/pixelwheels/racescreen/FinishedOverlay.java, core/src/com/agateau/ui/TableRowCreator.java
=> Finished overlay: fix column not fitting the screen in Esperanto

.changes/unreleased/Removed-20230929-080146.yaml, android/assets/ui/uiskin.gdxjson, core/src/com/agateau/pixelwheels/screens/SelectTrackScreen.java, core/src/com/agateau/pixelwheels/screens/TrackSelector.java, core/src/com/agateau/ui/menu/ButtonMenuItem.java, core/src/com/agateau/ui/menu/CornerMenuButton.java, core/src/com/agateau/ui/menu/GridMenuItem.java, core/src/com/agateau/ui/menu/Menu.java, core/src/com/agateau/ui/menu/RangeMenuItem.java, core/src/com/agateau/ui/menu/SwitchMenuItem.java, core/src/com/agateau/ui/menu/TabMenuItem.java
- Do not change the current item on mouse over
- Rework TrackSelector so that it can show more than 8 tracks
- MenuItems: always draw focus indicator *behind* the item
=> rework track selector

.changes/unreleased/Changed-20231003-163854.yaml, core-tests/src/com/agateau/pixelwheels/map/MaterialCheckerTest.java, core/src/com/agateau/pixelwheels/BodyIdentifier.java, core/src/com/agateau/pixelwheels/map/MaterialChecker.java, core/src/com/agateau/pixelwheels/racer/AIPilot.java, core/src/com/agateau/pixelwheels/screens/DebugScreen.java
- Add a debug option to tweak the AI speed limiter
- Make AIPilot avoid sand and water
- AIPilot: factorize body detection code
- Make AIPilot try to avoid other vehicles
- Add changelog entry
=> ai improvements

android/assets/screens/multiplayer.gdxui, core/src/com/agateau/pixelwheels/screens/MultiPlayerScreen.java, core/src/com/agateau/pixelwheels/screens/SelectChampionshipScreen.java, core/src/com/agateau/pixelwheels/screens/SelectTrackScreen.java, core/src/com/agateau/pixelwheels/screens/SelectVehicleScreen.java, core/src/com/agateau/ui/menu/FocusIndicator.java, core/src/com/agateau/ui/menu/Menu.java, core/src/com/agateau/ui/menu/SwitchMenuItem.java
- Fix focus indicator appearing dark sometimes
- refactor: add Menu.getMenuStyleByName() and use it
- MultiPlayerScreen: fix crash
=> misc ui fixes

core/src/com/agateau/pixelwheels/racer/AIPilot.java
- AIPilot: do not handle mines the same way we handle walls
- AIPilot: consider the way clear if there is a mine or vehicle
- AIPilot: treat "hole" material like walls
- AIPilot: do not give too much score to previous waypoint
=> ai pilot fixes

.changes/unreleased/Fixed-20240124-223814.yaml, core/src/com/agateau/pixelwheels/racescreen/Helicopter.java
- Make helicopter start from the closest edge instead of a corner
- Fix helicopter never being marked as finished
- Add changelog entry
=> improve helicopter start stop

docs/building.md
The po-compile target no longer exists.
=> Update build documentation

android/assets/po/ru.po
Do not partially translate names
=> Update Russian translation

android/assets/po/de.po
Tested at Debian, looks good to me.
_PS: Nice new track and "burning" effect!_ 😃
=> Update German Translation

docs/release-check-list.md, tools/packaging/linux/share/metainfo/com.agateau.PixelWheels.metainfo.xml
- **Update appstream metainfo file, following FlatHub failure**
- **Update release check list**
=> post release fixes

android/src/main/com/agateau/pixelwheels/android/AndroidLauncher.java, core/src/com/agateau/utils/log/NLog.java
- **Make sure log messages are not duplicated**
=> fix duplicated log messages

.changes/unreleased/Fixed-20250407-091707.yaml, android/AndroidManifest.xml, android/src/main/com/agateau/pixelwheels/android/AndroidLauncher.java, core/src/com/agateau/utils/PlatformUtils.java, desktop/src/com/agateau/pixelwheels/desktop/DesktopLauncher.java, desktop/src/com/agateau/pixelwheels/desktop/DesktopPlatformUtilsImpl.java
- **Fix links not opening on recent Android versions**
- **Reimplement Gdx.openURI to have more control**
=> fix support links

.github/workflows/changelog-check.yml, .github/workflows/main.yml
20.04 is no longer supported, move to 22.04.
=> Bump Ubuntu version

.changes/unreleased/Changed-20250521-173015.yaml, core/src/com/agateau/pixelwheels/GamePlay.java, core/src/com/agateau/pixelwheels/gameinput/DigitalSteering.java, core/src/com/agateau/pixelwheels/gameinput/GameInput.java, core/src/com/agateau/pixelwheels/gameinput/InputMapperInputHandler.java, core/src/com/agateau/pixelwheels/obstacles/Obstacle.java, core/src/com/agateau/pixelwheels/obstacles/ObstacleCreator.java, core/src/com/agateau/pixelwheels/obstacles/tiled/TiledObstacleCreator.java, core/src/com/agateau/pixelwheels/racer/PlayerPilot.java, core/src/com/agateau/pixelwheels/racer/Probe.java, core/src/com/agateau/pixelwheels/racer/Racer.java, core/src/com/agateau/pixelwheels/racer/Vehicle.java, core/src/com/agateau/pixelwheels/screens/DebugScreen.java, core/src/com/agateau/pixelwheels/utils/Box2DUtils.java, core/src/com/agateau/utils/KeyValueWriter.java, tools/speed-report-visualizer
- **Make KeyValueWriter write a JSONL file**
- **Remove unnecessary double-to-float conversion**
- **Fix static obstacles not having any restitution**
- **Improve speed report probe**
- **Add tool to visualize the speed report**
- **Make easy mode a bit faster**
- **Make walls a bit bumpier**
- **Make turbo less violent**
- **Reduce max steer at high speed**
- **Rework digital steering**
- **Add changelog entry**
=> improve steering

Makefile, desktop/src/com/agateau/pixelwheels/desktop/DesktopLauncher.java
- **Add Makefile target to test blank state**
- **Fix config migration messages not showing up**
- **Make testing blank state more reliable**
=> blank state

android/assets/po/ru.po
Hello, sorry for long absence, here is the translation.
=> Update Russian translation, add new strings

.changes/unreleased/Fixed-20250904-191654.yaml, android/assets/maps/tiny-sur-mer.tmx
=> Plug hole in Tiny-sur-mer
