core/src/com/agateau/pixelwheels/screens/SelectChampionshipScreen.java, core/src/com/agateau/pixelwheels/screens/SelectTrackScreen.java, core/src/com/agateau/pixelwheels/screens/SelectVehicleScreen.java, core/src/com/agateau/ui/menu/GridMenuItem.java
Make sure that if an already selected item (track, car or championship)
is touched / clicked, selection is confirmed and we proceed to next screen.
This make the ui more pleasant, and faster.
This contribution is sponsored by my company, Genymobile, for #hacktoberfest.
=> ui: touching a selected item validates user choice

core/src/com/agateau/ui/menu/MenuItemGroup.java
getCurrentItem() is returning null in the keyboard config
screen because there are no items to be focused. The
goUp() and goDown() methods did not account for that.
=> Fix crash when pressung up/down in keyboard config screen

core/src/com/agateau/pixelwheels/map/Track.java
Tthe TmxMapLoader assumes dependent files are siblings of the tmx file.
This causes a crash if PW_ASSETS_DIR is set when starting a race from a
checkout if game assets have not been processed, because in this case
the texture files are not in the same directory as the tmx file.
=> Fix crash when starting a race if PW_ASSETS_DIR is set

.github/workflows/main.yml
Do not build on push unless when pushing to master or dev.
=> Fix PR branches being build twice

android/build.gradle
This is required by Google since November 2021.
=> Bump Android target SDK version to 30

android/assets/po/bn.po, android/assets/po/es.po, android/assets/po/fr.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/assets/po/zh_CN.po, android/assets/screens/finishedoverlay.gdxui, core/src/com/agateau/pixelwheels/racescreen/FinishedOverlay.java
This PR works around the wording issue reported in #139, by using more a generic message. To make it more interesting, the message is randomly picked from a selection of congratulation messages.
=> Fix ambiguous "You broke a record" message

.changes/unreleased/Changed-20220313-181210.yaml, android/assets/po/bn.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/zh_CN.po, android/assets/screens/selectlanguage.gdxui, core/src/com/agateau/pixelwheels/Languages.java, core/src/com/agateau/pixelwheels/screens/ConfigScreen.java, core/src/com/agateau/pixelwheels/screens/SelectLanguageScreen.java, core/src/com/agateau/ui/menu/GridMenuItem.java
Languages are now selected from a dedicated screen instead of in a selector menu. This makes it easier to see all available languages, and faster to select one.
=> Replace language selector with a dedicated screen

tools/src/com/agateau/pixelwheels/tools/trackeditor/DeleteSectionAction.java, tools/src/com/agateau/pixelwheels/tools/trackeditor/Editor.java, tools/src/com/agateau/pixelwheels/tools/trackeditor/EditorActionStack.java, tools/src/com/agateau/pixelwheels/tools/trackeditor/InsertSectionAction.java, tools/src/com/agateau/pixelwheels/tools/trackeditor/MoveSelectionAction.java, tools/src/com/agateau/pixelwheels/tools/trackeditor/README.md, tools/src/com/agateau/pixelwheels/tools/trackeditor/TrackEditor.java, tools/src/com/agateau/pixelwheels/tools/trackeditor/TrackEditorScreen.java
- Implement redo, uses Shift+Ctrl+Z
- Draw the point number near selected points
=> trackeditor: implement redo and selected points labels

core/src/com/agateau/pixelwheels/bonus/Mine.java
Fixes regression where the mine shadow would disappear when driving over
water.
=> Always draw the mine shadow when attached

.changes/unreleased/Fixed-20220503-190241.yaml, android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/zh_CN.po, android/assets/vehicles/police.xml, android/assets/vehicles/red.xml, core/src/com/agateau/pixelwheels/map/Championship.java, core/src/com/agateau/pixelwheels/map/Track.java, core/src/com/agateau/pixelwheels/racer/Vehicle.java, core/src/com/agateau/pixelwheels/racescreen/FinishedOverlay.java, core/src/com/agateau/pixelwheels/racescreen/GameWorldImpl.java, core/src/com/agateau/pixelwheels/screens/ChampionshipFinishedScreen.java, core/src/com/agateau/pixelwheels/screens/SelectTrackScreen.java, core/src/com/agateau/pixelwheels/screens/SelectVehicleScreen.java, core/src/com/agateau/pixelwheels/screens/UnlockedRewardScreen.java, core/src/com/agateau/pixelwheels/vehicledef/VehicleCreator.java, core/src/com/agateau/pixelwheels/vehicledef/VehicleDef.java, core/src/com/agateau/pixelwheels/vehicledef/VehicleIO.java, docs/translations.md, tools/gettext/its/championships.its, tools/gettext/its/gdxui.loc, tools/gettext/its/pixelwheels.loc, tools/gettext/its/vehicles.its, tools/po-update
Make championship, track and vehicle names translatable.
Also: give more interesting names to some vehicles.
Fixes #168.
=> Make more texts translatable

android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/zh_CN.po, android/assets/screens/credits.gdxui, core/src/com/agateau/pixelwheels/screens/SelectLanguageScreen.java
Automatically sort languages in LanguageScreen.
Sort them in credits.md following the order produced by LanguageScreen.
=> Sort languages

.changes/unreleased/Developers-20220922-115524.yaml, core/src/com/agateau/pixelwheels/PwGame.java
Loading stats is OK and required to be able to work on any track. We just
want to prevent saving stats.
=> Fix tracks being locked when restarting with gameplay-locking options

.changes/unreleased/Fixed-20221010-200525.yaml, android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/messages.pot, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/sv.po, android/assets/po/zh_CN.po, core/src/com/agateau/pixelwheels/screens/GamepadConfigScreen.java
Just remove it: there is no such text in the equivalent keyboard config
screen.
Fixes #224
=> Gamepad config screen: fix "press key" text overflowing

.changes/unreleased/Fixed-20221211-104937.yaml, core/src/com/agateau/pixelwheels/screens/VehicleDrawer.java, core/src/com/agateau/ui/GLViewportSaver.java, docs/release-check-list.md
Do not stretch the scene to fill the screen when the display ratio is not 16:9.
Fixes #296
=> Fix stretched display on vehicle selection screen

android/assets/screens/selectlanguage.gdxui, core/src/com/agateau/pixelwheels/screens/SelectLanguageScreen.java, core/src/com/agateau/ui/menu/GridMenuItem.java
Fixes #310.
I didn't make the selector scrollable: 2 columns is good enough for now and I should even be able to extend to 3 if need be.
=> Use two columns for the language selector

.changes/unreleased/Developers-20230107-231622.yaml, android/src/main/com/agateau/pixelwheels/android/AndroidLauncher.java, android/src/main/com/agateau/pixelwheels/android/AndroidNLogPrinter.java, core-tests/src/com/agateau/utils/log/LogFilePrinterTests.java, core/src/com/agateau/pixelwheels/PwGame.java, core/src/com/agateau/utils/log/LogFilePrinter.java, core/src/com/agateau/utils/log/NLog.java, core/src/com/agateau/utils/log/NLogGdxApplicationLogger.java, core/src/com/agateau/utils/log/SystemErrPrinter.java, desktop/src/com/agateau/pixelwheels/desktop/DesktopLauncher.java
- Refactor NLog: now Gdx logs go through NLog instead of NLog using Gdx logs
- NLog now uses its own enum for log levels
- Add changelog entry
=> redirect gdx log

core/src/com/agateau/ui/menu/GridMenuItem.java
This fixes language selection when using the mouse.
=> Fix GridMenuItem mouseovers when ItemDirection set to TopToBottom

tools/po-update
This avoids useless pre-commit breaks.
=> po-update: do not update po files if only line numbers changed

.changes/unreleased/Fixed-20230726-231254.yaml, android/assets/maps/be.tmx, core/src/com/agateau/pixelwheels/obstacles/Obstacle.java
- Fix obstacle shadows not being drawn at the correct angle
- be: fix buildings showing under vehicles
=> fix obstacle shadows

.changes/unreleased/Changed-20230811-081227.yaml, core-tests/src/com/agateau/utils/tests/AgcMathUtilsTests.java, core/src/com/agateau/pixelwheels/racer/VehicleRenderer.java, core/src/com/agateau/utils/AgcMathUtils.java
- Snap angles
- Do not draw slightly rotated vehicles on the start line
=> snap angles

android/assets/po/de.po
Tested at Xubuntu 22.04, but without a gamepad.
=> Update German translation

.changes/unreleased/Fixed-20230911-183603.yaml, core-tests/src/com/agateau/pixelwheels/GameConfigTest.java, core-tests/src/com/agateau/utils/TestGdxPreferences.java, core/src/com/agateau/pixelwheels/GameConfig.java, core/src/com/agateau/pixelwheels/gameinput/GameInputHandlerFactories.java
Ensures a touch-screen device falls back to a touch-screen input handler
instead of the keyboard handler.
Add tests.
Should fix #398
=> Use a predefined order to decide fall back input handlers

core/src/com/agateau/pixelwheels/bonus/Missile.java
This has been reported by Google Play review system as a crash in Missile.explode(), caused by mSoundPlayer being null:
```
Exception java.lang.NullPointerException: Attempt to invoke interface method 'void com.agateau.pixelwheels.sound.SoundPlayer.stop()' on a null object reference
at com.agateau.pixelwheels.bonus.Missile.explode (Missile.java:343)
at com.agateau.pixelwheels.bonus.Missile.preSolve (Missile.java:368)
at com.agateau.pixelwheels.racescreen.GameWorldImpl.preSolve (GameWorldImpl.java:374)
at com.badlogic.gdx.physics.box2d.World.preSolve (World.java:1003)
at com.badlogic.gdx.physics.box2d.World.jniStep
at com.badlogic.gdx.physics.box2d.World.step (World.java:691)
at com.agateau.pixelwheels.racescreen.GameWorldImpl.act (GameWorldImpl.java:193)
at …
```
=> Fix rare crash when missile explodes before audioRender() has been called

android/assets/ui/uiskin.gdxjson, core/src/com/agateau/ui/menu/FocusIndicator.java, core/src/com/agateau/ui/menu/GridMenuItem.java
- Make focus indicator glow, set default padding back to 2
- Make selected item half-transparent
=> animated focus indicator

.changes/unreleased/Added-20240505-230711.yaml, .github/workflows/main.yml, android/assets/po/bn.po, android/assets/po/de.po, android/assets/po/eo.po, android/assets/po/es.po, android/assets/po/eu.po, android/assets/po/fr.po, android/assets/po/hu.po, android/assets/po/it_IT.po, android/assets/po/messages.pot, android/assets/po/nl.po, android/assets/po/pl.po, android/assets/po/ru.po, android/assets/po/sv.po, android/assets/po/tr.po, android/assets/po/zh_CN.po, core/src/com/agateau/pixelwheels/GameConfig.java, core/src/com/agateau/pixelwheels/GamePlay.java, core/src/com/agateau/pixelwheels/PrefConstants.java, core/src/com/agateau/pixelwheels/racescreen/CameraUpdater.java, core/src/com/agateau/pixelwheels/racescreen/FreeCameraUpdater.java, core/src/com/agateau/pixelwheels/racescreen/GameRenderer.java, core/src/com/agateau/pixelwheels/racescreen/HeadingUpCameraUpdater.java, core/src/com/agateau/pixelwheels/racescreen/RaceScreen.java, core/src/com/agateau/pixelwheels/racescreen/RacerCameraUpdater.java, core/src/com/agateau/pixelwheels/screens/ConfigScreen.java, tools/apply-codingstyle
I'm not a game dev myself, just came to this game by accident and enjoyed it.
But currently as "retro" as it is, the driving experience feels more like controlling a RC car model. I think I would enjoy more in more realistic feeling of heading up mode, then tinkered with the code base, and come with a basic hack of the desired feel.
Current changes are way very basic and lack a lot of adjustments to get it all right, yet it's only 3 lines changed atm.
I'd like to know what you think about this mode before any proceeding, and definitely need your help and efforts to get it all done.
A few of my thoughts what can/shall be done:
1. make it an option to race in this mode, maybe better along with portrait display mode of the phone
2. proper camera handling when the car is moving back
3. fix …
=> heading-up-mode

.changes/unreleased/Fixed-20240512-164437.yaml, core/src/com/agateau/pixelwheels/racescreen/Helicopter.java
bugfix: helicopter sound stays forever if was playing when back from finish screen.
=> bugfix: helicopter sound stays forever if was playing when back from finish screen

android/assets/screens/selecttrack.gdxui, android/assets/ui/uiskin.gdxjson, core/src/com/agateau/pixelwheels/screens/SelectTrackScreen.java, core/src/com/agateau/ui/anchor/PositionRule.java, core/src/com/agateau/ui/menu/FocusIndicator.java, core/src/com/agateau/ui/menu/GridMenuItem.java
- **PositionRule: Improve documentation**
- **SelectTrack: set a different background for the championship selector**
- **GridMenuItem: highlight the current item when unfocused**
- **GridMenuItem: make internal method private**
- **GridMenuItem: avoid infinite loop when calling setCurrentIndex()**
- **GridMenuItem: clear selected index when current**
- **GridMenuItem: remove touch-specific behavior in setCurrentAndSelect**
- **SelectTrack: fix track list not changing immediately when championship is clicked in touch mode**
- **ImageButton: fix image being too high in the button frame**
=> fix select track nav

.changes/unreleased/Changed-20240826-080222.yaml, core/src/com/agateau/pixelwheels/gameinput/DigitalSteering.java, core/src/com/agateau/pixelwheels/gameinput/InputMapperInputHandler.java, core/src/com/agateau/pixelwheels/gameinput/PieTouchInputHandler.java, core/src/com/agateau/pixelwheels/gameinput/SidesTouchInputHandler.java
Use the same steering algorithm for all input methods (touch, keyboard or
gamepad)
=> Unify digital steering

android/assets/po/fr.po, android/assets/screens/config.gdxui, core/src/com/agateau/pixelwheels/screens/ConfigScreen.java, core/src/com/agateau/ui/uibuilder/UiBuilder.java
- **Update French translation**
- **gdxui: Fix Menu.labelColumnWidth not supporting units**
- **ConfigScreen: make label width larger, define it in gdxui**
=> update fr translation

tools/packaging/linux/share/metainfo/com.agateau.PixelWheels.metainfo.xml
Based on what is already available in the [LinuxPhoneApps listing](https://linuxphoneapps.org/games/com.agateau.pixelwheels) I added some missing metainfo:
- Adds vcs-browser url
=> Complement com.agateau.PixelWheels.metainfo.xml
